FROM confluentinc/cp-kafka-connect:7.3.0

RUN confluent-hub install --no-prompt debezium/debezium-connector-postgresql:2.2.1
RUN confluent-hub install --no-prompt jcustenborder/kafka-connect-redis:latest
